source 'https://supermarket.chef.io'

metadata

cookbook 'packer',                git: 'https://github.com/zevin/chef-packer.git'
cookbook 's3_file',               git: 'https://github.com/reancloud/s3_file.git'
cookbook 'jq',                    git: 'https://github.com/reancloud/chef-jq.git'
cookbook 'selinux_policy',        git: 'https://github.com/reancloud/selinux_policy.git'
cookbook 'terraform',             git: 'https://github.com/reancloud/chef-terraform.git'
#cookbook 'REAN-Java',             git: 'https://<private_access_token>:x-oauth-basic@github.com/reancloud/REAN-Java.git'
#cookbook 'rvm',                   git: 'https://<private_access_token>:x-oauth-basic@github.com/reancloud/chef-rvm.git', tag: '0.1.5'
#cookbook 'REAN-Java',             git: 'git@github.com:reancloud/REAN-Java.git'
cookbook 'rvm',                   git: 'git@github.com:reancloud/chef-rvm.git', tag: '0.1.5'
cookbook 'java'
